cliArgs:
  geometry: false # retrieve geometry (-g)
  threads: 4 # number of threads to use (-t)
  explore: 5 # exploration level to use (0..5) (-x)
  limit: '1mb' # max request size
  logdir: '/var/lib/vroom-express/tmp' # the path for the logs relative to ./src
  maxlocations: 1000 # max number of jobs/shipments locations
  maxvehicles: 200 # max number of vehicles
  override: true # allow cli options override (-g, -t and -x)
  path: '/vroom/bin/' # VROOM path (if not in $PATH)
  port: 3001 # expressjs port
  router: 'ors' # routing backend (osrm, libosrm or ors)
  timeout: 300000 # milli-seconds
  baseurl: '/' #base url for api
routingServers:
  ors:
    driving-car:
      host: 'openrouteservice-app'
      port: '8080'
    driving-hgv:
      host: 'openrouteservice-app'
      port: '8080'
    cycling-regular:
      host: 'openrouteservice-app'
      port: '8080'
    foot-walking:
      host: 'openrouteservice-app'
      port: '8080'
