FROM httpd:2.4

# install xinetd to make it possible to add check_mk to the Docker container
# procps (to be precise: the 'pgrep' binary) is required by the postinst script of check-mk-agent
COPY thirdparty/check-mk-agent_1.5.0p24-1_all.deb /tmp/check-mk-agent.deb
RUN apt-get -qq update && apt-get -qq upgrade -f && apt-get install -qq -y xinetd procps
RUN dpkg -i /tmp/check-mk-agent.deb && rm /tmp/check-mk-agent.deb

# Es wird xinetd in den Entrypoint reingepatcht, damit der check-mk agent abgerufen werden kann.
RUN sed -e '2ixinetd' -i /usr/local/bin/httpd-foreground

COPY httpd.conf /usr/local/apache2/conf/httpd.conf

# Required to retrieve host IP
RUN apt-get install -qq -y iproute2

COPY start_httpd.sh /

# Copy web application (build see our fork of the openrouteservice-app repository)
RUN mkdir /ors-web
COPY webapp/ /ors-web

CMD /bin/bash /start_httpd.sh
