FROM httpd:2.4

ARG ORS_WEB_ZIP_URL_BASE=https://github.com/GIScience/openrouteservice-app/archive
ARG ORS_WEB_BRANCH_TAG
ARG ORS_WEB_BRANCH_TAG_IN_ZIP
ARG TILE_URLBASE_BKG
ARG TILE_URLBASE_OSMDE
ARG TILE_URLBASE_BASIC
ARG TILE_URLBASE_LABELS
ARG GEOCODE_URL_BASE

# install xinetd to make it possible to add check_mk to the Docker container
# procps (to be precise: the 'pgrep' binary) is required by the postinst script of check-mk-agent
COPY thirdparty/check-mk-agent_1.5.0p24-1_all.deb /tmp/check-mk-agent.deb
RUN apt-get -qq update && apt-get -qq upgrade -f && apt-get install -qq -y xinetd procps
RUN dpkg -i /tmp/check-mk-agent.deb && rm /tmp/check-mk-agent.deb

# Es wird xinetd in den Entrypoint reingepatcht, damit der check-mk agent abgerufen werden kann.
RUN sed -e '2ixinetd' -i /usr/local/bin/httpd-foreground

# Install GPG key for NodeJS
RUN apt-get -qq install -y curl wget gnupg patch unzip git && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash && \
    apt-get -qq -y update && \
    apt-get -qq install -y nodejs && \
    mkdir /ors-web

COPY patches/app.js.patch patches/ors-utils-service.js.patch patches/Gruntfile.js.patch patches/ors-map.js.patch patches/ors-request-service.js.patch /ors-web/

COPY run_grunt.sh /

RUN cd /ors-web && wget --quiet -O /ors-web.zip $ORS_WEB_ZIP_URL_BASE/$ORS_WEB_BRANCH_TAG.zip && unzip -q -d /ors-web /ors-web.zip && mv /ors-web/openrouteservice-app-$ORS_WEB_BRANCH_TAG_IN_ZIP/* /ors-web/openrouteservice-app-$ORS_WEB_BRANCH_TAG_IN_ZIP/.b* /ors-web && \
    cd /ors-web && npm install && \
    node_modules/bower/bin/bower install --quiet --allow-root && \
    cd /ors-web/bower_components/angularjs-slider && npm install --quiet && cd /ors-web && \
    cd /ors-web && cp Gruntfile.default.js Gruntfile.js && \
    patch app/js/app.js app.js.patch && \
    patch Gruntfile.js Gruntfile.js.patch && \
    patch app/components/ors-map/ors-map.js ors-map.js.patch && \
    patch app/infrastructure/ors-request-service.js ors-request-service.js.patch && \
    patch app/infrastructure/ors-utils-service.js ors-utils-service.js.patch && \
    sed -i \
      -e "s,XXX_TILE_URL_BKG,$TILE_URLBASE_BKG,g" \
      -e "s,XXX_TILE_URL_OSMDE,$TILE_URLBASE_OSMDE,g" \
      -e "s,XXX_TILE_URL_BASIC,$TILE_URLBASE_BASIC,g" \
      -e "s,XXX_TILE_URL_LABELS,$TILE_URLBASE_LABELS,g" \
      -e "s,XXX_GEOCODE_URL_BASE,$GEOCODE_URL_BASE,g" \
      Gruntfile.js && \
    rm *.patch && \
    cp app/weathercheck.default.txt app/weathercheck.txt && \
    chmod 755 /run_grunt.sh && /run_grunt.sh && rm /run_grunt.sh

COPY httpd.conf /usr/local/apache2/conf/httpd.conf
