FROM ubuntu:focal

ENV MAVEN_OPTS="-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
ENV MAVEN_CLI_OPTS="--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

ARG APP_CONFIG
ARG JAVA_OPTS
ARG ORS_ZIP_URL_BASE=https://github.com/GIScience/openrouteservice/archive
ARG ORS_BRANCH_TAG=v6.0.0
ARG ORS_BRANCH_TAG_IN_ZIP=6.0.0
ARG DEBIAN_FRONTEND=noninteractive


# Install required deps
RUN apt-get update -qq && apt-get install -qq -y openjdk-11-jdk bash locales wget maven osmium-tool jq \
    build-essential cmake libboost-dev libexpat1-dev zlib1g-dev libbz2-dev zip
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN apt-get update && apt-get install -qq -y python3-pip python3 && pip3 install osmium


# Download Openrouteservice source code and build it
RUN mkdir -p /ors-core/ && \
    wget --quiet -O /ors.zip $ORS_ZIP_URL_BASE/$ORS_BRANCH_TAG.zip && \
    unzip -q -d /ors-core/ /ors.zip && mv /ors-core/openrouteservice-$ORS_BRANCH_TAG_IN_ZIP/openrouteservice/ /ors-core/openrouteservice/ && \
    rm -rf /ors-core/openrouteservice-$ORS_BRANCH_TAG_IN_ZIP/* && \
    rm /ors.zip
    
COPY bfs-pom.xml /ors-core/openrouteservice/

# Copy osm data file, config and cache if provided (ors will download otherwise)
COPY $APP_CONFIG /ors-core/openrouteservice/src/main/resources/app.config

WORKDIR /ors-core

# set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64

# Build Openrouteservice
RUN mvn -q -f ./openrouteservice/bfs-pom.xml clean compile assembly:single -DskipTests

# Create backup of original configuration
RUN cp /ors-core/openrouteservice/src/main/resources/app.config /ors-core/openrouteservice/src/main/resources/app.config.orig && \
    cp /ors-core/openrouteservice/src/main/resources/logs/PRODUCTION_LOGGING.json /ors-core/openrouteservice/src/main/resources/logs/PRODUCTION_LOGGING.json.orig

COPY germany-100km.poly /ors-core/
COPY update.sh /ors-core/update.sh

# Run Openrouteservice
CMD /bin/bash /ors-core/update.sh
