FROM postgis/postgis:13-3.1

ARG NOMINATIM_TARBALL_URL=https://nominatim.org/release/Nominatim-3.4.1.tar.bz2
ARG DEBIAN_FRONTEND=noninteractive

# PHP is needed to satisfy build dependencies (Nominatim CMake)
# ca-certificates is needed for Wget to verify nominatim.org
RUN apt-get update && apt-get upgrade -fy && apt-get install --no-install-recommends -y xinetd wait-for-it wget build-essential cmake g++ libboost-dev libboost-system-dev libboost-filesystem-dev libexpat1-dev zlib1g-dev libxml2-dev libbz2-dev libpq-dev libproj-dev postgresql-server-dev-13 unzip php ca-certificates pyosmium locales locales-all
ENV LC_ALL "de_DE.UTF-8"
ENV LANG "de_DE.UTF-8"
ENV LANGUAGE "de_DE.UTF-8"

COPY thirdparty/check-mk-agent_1.5.0p24-1_all.deb /tmp/check-mk-agent.deb
RUN dpkg -i /tmp/check-mk-agent.deb && rm /tmp/check-mk-agent.deb

COPY thirdparty/mk_postgres /usr/lib/check_mk_agent/plugins/mk_postgres

RUN mkdir -p /nominatim && cd /nominatim && wget --quiet -O nominatim.tar.bz2 $NOMINATIM_TARBALL_URL && tar -xjf nominatim.tar.bz2 &&  mv Nominatim-*/* . && rm -rf Nominatim-* && rm nominatim.tar.bz2 && mkdir -p build && cd build && cmake .. && make -s -j2 nominatim_lib

RUN sed -i 's/#wal_level.*/wal_level = logical/g' /usr/share/postgresql/postgresql.conf.sample
RUN sed -i 's/#shared_buffers.*/shared_buffers = 16GB/g' /usr/share/postgresql/postgresql.conf.sample
RUN sed -i 's/#work_mem.*/work_mem = 128MB/g' /usr/share/postgresql/postgresql.conf.sample
RUN sed -i 's/#mainentenance_work_mem.*/mainentenance_work_mem = 256MB/g' /usr/share/postgresql/postgresql.conf.sample

COPY init_nominatim.sh /docker-entrypoint-initdb.d/init_nominatim.sh

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT /entrypoint.sh
